### ISSUE TITLE
Invalidate authentication token

### ISSUE THREAD

**Issue by mspl13** [albalitz/save-api#3]
It would be nice to be able to invalidate authentication tokens on request.

**Comment by albalitz** [comment]
Agreed. I'll look into this.

**Comment by albalitz** [comment]
Okay, I think I've come up with a solution for this. I'm not that experienced with APIs, so I think it'd be good to have a second opinion on this. (@mspl13)

I'll save a `User`'s valid tokens in the database. Every time a new token is generated, it's added to the `User`'s valid tokens.
Every time an expired token is used or explicitly requested to be invalidated, the token is removed.

Let's call the route for the explicit invalidation /token/invalidate.
Additionally, I think a /token/invalidate/all route could come in handy some time later to allow a client to let the user "sign out of every session (using token auth)".

**Comment by mspl13** [comment]
I don't know if that really the case but I think your API so far generates always the same token as long as it is still valid. That would mean that you will never have multiple tokens. Is that true?

**Comment by albalitz** [comment]
No, I just tested it, I get a different token with every request.
They look very similar though - the first two parts are the same I think.

**Comment by mspl13** [comment]
> They look very similar though
That makes sense. It seems I didn't look close enough. :+1:

Other than that I have no immediate concerns with that approach.
